## NumPy

In [1]:
import numpy as np

In [2]:
data1 = [1,2,3,4,5]
np_data1 = np.array(data1)
np_data1

array([1, 2, 3, 4, 5])

In [3]:
type(np_data1)

numpy.ndarray

In [4]:
np_data1.ndim

1

In [5]:
data2 = [[1,2,3,4],[5,6,7,8]]
np_data2 = np.array(data2)
np_data2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
np_data2.ndim

2

In [9]:
mat_data = np.matrix(data1)
type(mat_data)

numpy.matrix

In [10]:
mat_data.ndim

2

In [11]:
mat_data2 = np.matrix(data2)

In [12]:
mat_data2.ndim

2

In [14]:
np_arr = np.asanyarray(data1)
type(np_arr)

numpy.ndarray

In [15]:
np_arr.ndim

1

In [17]:
my_arr = np.fromfunction(lambda x,y: x==y, (3,3))
my_arr

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
x = (i**2 for i in range(5))
x

<generator object <genexpr> at 0x000002BAFD132960>

In [20]:
for i in x:
    print(i)

0
1
4
9
16


In [22]:
list(x)

[0, 1, 4, 9, 16]

In [29]:
np.fromiter(x,int)

array([ 0,  1,  4,  9, 16])

In [32]:
np.fromstring("24 25 26", sep=" ")

array([24., 25., 26.])

In [33]:
np.fromstring("24,25,26", sep=",")

array([24., 25., 26.])

In [35]:
np_data1

array([1, 2, 3, 4, 5])

In [34]:
np_data1.size

5

In [37]:
np_data2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
np_data2.shape

(2, 4)

In [40]:
np_data1.dtype

dtype('int32')

In [41]:
np_data2.ndim

2

In [45]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [46]:
np.arange(0.1,20.10)

array([ 0.1,  1.1,  2.1,  3.1,  4.1,  5.1,  6.1,  7.1,  8.1,  9.1, 10.1,
       11.1, 12.1, 13.1, 14.1, 15.1, 16.1, 17.1, 18.1, 19.1])

In [47]:
list(np.arange(0.1,20.10))

[0.1,
 1.1,
 2.1,
 3.1,
 4.1,
 5.1,
 6.1,
 7.1,
 8.1,
 9.1,
 10.1,
 11.1,
 12.1,
 13.1,
 14.1,
 15.1,
 16.1,
 17.1,
 18.1,
 19.1]

In [48]:
np.linspace(1,5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [49]:
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [50]:
np.logspace(1,5, 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [51]:
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
data1 = np.ones((3,4))
data1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
data1+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [57]:
data1 = np.empty((3,4))
data1

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [60]:
data1 = np.eye(5)
data1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
import pandas as pd

In [61]:
pd.DataFrame(data1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [62]:
np.random.rand(2,3)

array([[0.94475843, 0.66625442, 0.96205953],
       [0.86446637, 0.82848338, 0.13818836]])

In [63]:
np.random.randn(2,3)

array([[-0.11068362, -1.49905764, -1.09592161],
       [-0.44808752,  1.43278643, -0.84853246]])

In [65]:
data = np.random.randint(1,5, (3,4))
data

array([[4, 4, 4, 2],
       [1, 3, 1, 1],
       [1, 4, 2, 3]])

In [67]:
data.shape

(3, 4)

In [68]:
data.size

12

In [69]:
data.reshape(6,2)

array([[4, 4],
       [4, 2],
       [1, 3],
       [1, 1],
       [1, 4],
       [2, 3]])

In [73]:
data.reshape(4,-1)

array([[4, 4, 4],
       [2, 1, 3],
       [1, 1, 1],
       [4, 2, 3]])

In [81]:
data.reshape(4,-1944040)

array([[4, 4, 4],
       [2, 1, 3],
       [1, 1, 1],
       [4, 2, 3]])

In [75]:
data.reshape(2,3,2)

array([[[4, 4],
        [4, 2],
        [1, 3]],

       [[1, 1],
        [1, 4],
        [2, 3]]])

In [77]:
data[data>0]

array([4, 4, 4, 2, 1, 3, 1, 1, 1, 4, 2, 3])

In [79]:
data[(data>0) & (data<4)]

array([2, 1, 3, 1, 1, 1, 2, 3])

In [82]:
data

array([[4, 4, 4, 2],
       [1, 3, 1, 1],
       [1, 4, 2, 3]])

In [84]:
data[:2,:3]

array([[4, 4, 4],
       [1, 3, 1]])

In [85]:
data1 = np.random.randint(1,3,(3,3))
data2 = np.random.randint(1,5,(3,3))

In [86]:
data1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [87]:
data2

array([[3, 2, 2],
       [3, 3, 3],
       [4, 3, 2]])

In [88]:
data = data1+data2
data

array([[4, 3, 3],
       [4, 4, 5],
       [6, 4, 3]])

In [89]:
data1@data2

array([[10,  8,  7],
       [14, 11,  9],
       [13, 10,  9]])

In [100]:
data1 = np.random.randint(1,3,(3,4))
data1

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [103]:
x= np.array([1])
x

array([1])

In [104]:
data1+x

array([[3, 2, 2, 3],
       [3, 3, 3, 2],
       [2, 3, 3, 2]])

In [105]:
data1

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [107]:
data1.T

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 2],
       [2, 1, 1]])

In [109]:
np.sqrt(data1.T)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [110]:
np.log10(data1.T)

array([[0.30103, 0.30103, 0.     ],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.30103],
       [0.30103, 0.     , 0.     ]])

In [112]:
np.exp(data1.T)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [113]:
np.min(data1)

1

In [114]:
np.max(data1)

2

In [115]:
data1

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [116]:
data1.flatten()

array([2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1])

In [119]:
np.expand_dims(data1, axis=0)

array([[[2, 1, 1, 2],
        [2, 2, 2, 1],
        [1, 2, 2, 1]]])

In [118]:
np.squeeze(data1)

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [120]:
data1

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [123]:
np.repeat(data1,3)

array([2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1])

In [125]:
np.roll(data1,4)

array([[1, 2, 2, 1],
       [2, 1, 1, 2],
       [2, 2, 2, 1]])

In [127]:
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [128]:
~data1

array([[-3, -2, -2, -3],
       [-3, -3, -3, -2],
       [-2, -3, -3, -2]])

In [129]:
data1

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [131]:
arr_data = np.array(["Mango", "Apple", "Banana"])
arr_data

array(['Mango', 'Apple', 'Banana'], dtype='<U6')

In [133]:
np.char.upper(arr_data)

array(['MANGO', 'APPLE', 'BANANA'], dtype='<U6')

In [134]:
np.char.capitalize(arr_data)

array(['Mango', 'Apple', 'Banana'], dtype='<U6')

In [135]:
np.char.title(arr_data)

array(['Mango', 'Apple', 'Banana'], dtype='<U6')

In [136]:
np.sin(data1)

array([[0.90929743, 0.84147098, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.90929743, 0.84147098],
       [0.84147098, 0.90929743, 0.90929743, 0.84147098]])

In [137]:
np.cos(data1)

array([[-0.41614684,  0.54030231,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684, -0.41614684,  0.54030231],
       [ 0.54030231, -0.41614684, -0.41614684,  0.54030231]])

In [138]:
np.power(data1,2)

array([[4, 1, 1, 4],
       [4, 4, 4, 1],
       [1, 4, 4, 1]], dtype=int32)

In [139]:
np.mean(data1)

1.5833333333333333

In [140]:
np.median(data1)

2.0

In [141]:
data1

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [142]:
data2

array([[3, 2, 2],
       [3, 3, 3],
       [4, 3, 2]])

In [145]:
data3 = np.random.randint(1,3, (3,4))
data3

array([[1, 1, 1, 1],
       [2, 1, 2, 1],
       [1, 2, 2, 2]])

In [146]:
data1-data3

array([[ 1,  0,  0,  1],
       [ 0,  1,  0,  0],
       [ 0,  0,  0, -1]])

In [147]:
np.subtract(data1, data3)

array([[ 1,  0,  0,  1],
       [ 0,  1,  0,  0],
       [ 0,  0,  0, -1]])

In [148]:
data1

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [149]:
np.sort(data1)

array([[1, 1, 2, 2],
       [1, 2, 2, 2],
       [1, 1, 2, 2]])

In [150]:
data1

array([[2, 1, 1, 2],
       [2, 2, 2, 1],
       [1, 2, 2, 1]])

In [155]:
data = np.array([2,5,1,90,3,40])
np.sort(data)

array([ 1,  2,  3,  5, 40, 90])

In [157]:
np.searchsorted(data, 5)               

1

In [159]:
np.count_nonzero(data1)

12

In [162]:
np.where(data>3)

(array([1, 3, 5], dtype=int64),)

In [163]:
np.extract(data>3, data)

array([ 5, 90, 40])

In [165]:
data

array([ 2,  5,  1, 90,  3, 40])

In [166]:
data.byteswap(True)

array([  33554432,   83886080,   16777216, 1509949440,   50331648,
        671088640])

In [167]:
data

array([  33554432,   83886080,   16777216, 1509949440,   50331648,
        671088640])

In [168]:
a = np.array([1,2,3,4,5])
b = a

In [169]:
b

array([1, 2, 3, 4, 5])

In [170]:
b[0]=10

In [171]:
a

array([10,  2,  3,  4,  5])

In [172]:
c = np.copy(a)
c

array([10,  2,  3,  4,  5])

In [173]:
c[1]=20

In [174]:
c

array([10, 20,  3,  4,  5])

In [175]:
a

array([10,  2,  3,  4,  5])

In [178]:
d = a.view()
d

array([10,  2,  3,  4,  5])

In [179]:
a[2]=30

In [180]:
a

array([10,  2, 30,  4,  5])

In [181]:
d

array([10,  2, 30,  4,  5])

In [182]:
import numpy.matlib as nm

In [186]:
nm.zeros((3,5))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [187]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [190]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [212]:
data1 = np.random.randint(2,5, (3,3))
data2 = np.random.randint([[2,5,4], [3,5,6], [4,3,4]])

In [213]:
data1

array([[4, 4, 4],
       [3, 3, 3],
       [3, 4, 3]])

In [214]:
data2

array([[1, 4, 3],
       [1, 4, 5],
       [2, 1, 0]])

In [215]:
np.dot(data1,data2)

array([[16, 36, 32],
       [12, 27, 24],
       [13, 31, 29]])

In [216]:
data1@data2

array([[16, 36, 32],
       [12, 27, 24],
       [13, 31, 29]])