## Assignment on NumPy Basic

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

Yes, there is a difference in the data type of variables **list_** and **array_list**. The variable **list_** is a Python list which can contain elements of different data types whereas **array_list** is a NumPy array which can only contain elements of the same data type.

To print the data types of both variables, we can use the type() function in Python as follows:

In [11]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

In [16]:
for item in list_:
    print(type(item))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [17]:
for item in array_list:
    print(type(item))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)**

In [21]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)
print(array_list)

[1 2 3 4 5]


In [22]:
for item in array_list:
    print(type(item))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


**Q4. Write a code to find the following characteristics of variable, num_array:**
* shape
* size

In [27]:
# Create a NumPy Array
data = np.random.randint(1,5,(3,3))
data

array([[2, 1, 1],
       [3, 4, 2],
       [3, 2, 4]])

In [25]:
data.shape

(3, 3)

In [26]:
data.size

9

**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.**
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [31]:
data = np.zeros((3,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Q6. Create an identity matrix of shape (5,5) using numpy functions?**
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [38]:
# We can use identiy function
data = np.identity(5)
data

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
# Or we can also use eye function
data = np.eye(5)
data

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])