## Logistic Regression 

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load IRIS Dataset
from sklearn.datasets import load_iris
dataset = load_iris()
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [3]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
df['class']=dataset.target

In [7]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     class  
145      2  
146      2  
147      2  
148      2  
149      2

In [8]:
df['class'].unique()

array([0, 1, 2])

In [9]:
df['class'].value_counts()

0    50
1    50
2    50
Name: class, dtype: int64

In [10]:
# Make it binary classification
# So we have to remove class 2

df_copy = df[df['class'] != 2]
df_copy.shape

(100, 5)

In [11]:
df_copy['class'].unique()

array([0, 1])

In [12]:
df_copy['class'].value_counts()

0    50
1    50
Name: class, dtype: int64

In [14]:
# Divide independent and dependent features
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:,-1]

In [15]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [16]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [17]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

In [18]:
# Create Logistic Regression with default parameters
from sklearn.linear_model import LogisticRegression
classification = LogisticRegression()

In [19]:
classification

LogisticRegression()

In [19]:
# Fit the model
classification.fit(X_train, y_train)

LogisticRegression()

In [20]:
# Predict the model
y_pred = classification.predict(X_test)

## Confusion Metrics, Accuracy, Classification Report

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))

[[12  0]
 [ 0  8]]


In [22]:
print(accuracy_score(y_test, y_pred))

1.0


In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [20]:
# Cross Validation
from sklearn.model_selection import KFold
cv = KFold(n_splits=5, shuffle=True)

In [21]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [22]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classification, X_train, y_train, scoring='accuracy', cv=cv)
scores

array([1., 1., 1., 1., 1.])

In [23]:
np.mean(scores)

1.0

## Hyperparameter Tuning Using GridsearchCV

In [30]:
from sklearn.model_selection import GridSearchCV

# -------| Ignore Errors |---------
import warnings
warnings.filterwarnings('ignore')
# ---------------------------------

In [36]:
# Define the parameters
parameters = {'penalty':('l1', 'l2', 'elasticnet'), 'C':[1,10,20,30], 'solver':('lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga')}

In [37]:
classifier = LogisticRegression()

In [38]:
clf = GridSearchCV(classifier, param_grid=parameters, cv=5)

In [39]:
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ('lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga')})

In [40]:
# Now get the best parameters
clf.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [41]:
clf.best_score_

1.0

In [42]:
# Now make model with this hyperparameter tuning parameters
classifier = LogisticRegression(C=1, penalty='l1', solver='liblinear')
classifier

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [44]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1, penalty='l1', solver='liblinear')

In [49]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
accuracy_score(y_test, y_pred)

1.0

In [52]:
print(confusion_matrix(y_test, y_pred))

[[12  0]
 [ 0  8]]


In [53]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [48]:
# Predict the probality of the binaty output
classifier.predict_proba(X_test)

array([[6.54497828e-04, 9.99345502e-01],
       [4.88823968e-03, 9.95111760e-01],
       [4.80836124e-03, 9.95191639e-01],
       [9.66454780e-01, 3.35452204e-02],
       [9.80455910e-01, 1.95440900e-02],
       [9.82750297e-01, 1.72497028e-02],
       [9.97175800e-01, 2.82420037e-03],
       [1.05733264e-02, 9.89426674e-01],
       [9.91474944e-01, 8.52505641e-03],
       [9.89544466e-01, 1.04555343e-02],
       [9.88509773e-01, 1.14902268e-02],
       [9.55180533e-01, 4.48194671e-02],
       [2.43736105e-03, 9.97562639e-01],
       [9.98005242e-01, 1.99475826e-03],
       [3.39817485e-03, 9.96601825e-01],
       [9.91739603e-01, 8.26039730e-03],
       [1.86230270e-03, 9.98137697e-01],
       [1.74773524e-03, 9.98252265e-01],
       [9.66454780e-01, 3.35452204e-02],
       [9.82750297e-01, 1.72497028e-02]])

## Hyperparameter Tuning using Randomozed Search CV

In [54]:
from sklearn.model_selection import RandomizedSearchCV

In [59]:
rand_clf = RandomizedSearchCV(classifier, param_distributions=parameters, cv=5, n_iter=20)
rand_clf

RandomizedSearchCV(cv=5,
                   estimator=LogisticRegression(C=1, penalty='l1',
                                                solver='liblinear'),
                   n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet'),
                                        'solver': ('lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga')})

In [60]:
rand_clf.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=LogisticRegression(C=1, penalty='l1',
                                                solver='liblinear'),
                   n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet'),
                                        'solver': ('lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga')})

In [61]:
rand_clf.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 20}

In [62]:
classifier = LogisticRegression(C=20, penalty='l1', solver='saga')
classifier.fit(X_train, y_train)

LogisticRegression(C=20, penalty='l1', solver='saga')

In [64]:
y_pred = classifier.predict(X_test)

In [66]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))

1.0


In [67]:
print(confusion_matrix(y_test, y_pred))

[[12  0]
 [ 0  8]]


In [68]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

