## Perceptron Logic Gate Operations

In [1]:
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

In [2]:
class Perceptron:
    def __init__(self, learning_rate, bias, epochs):
        self.learning_rate = learning_rate
        self.bias = bias
        self.epochs = epochs
        self.weights = np.random.randn(2) * 1e-4
        
        print(f"Initial Weights : {self.weights}")
    
    def activationFunction(self,inputs):
        z = np.dot(inputs,self.weights) + self.bias*(len(self.weights))
        return np.where(z>0,1,0)
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        for epoch in range(self.epochs):
            print(f"Epoch {epoch+1}")
            y_hat = self.activationFunction(self.X)
            print(f"Predicted Value {y_hat}")
            
            error = self.y-y_hat
            print(f"Error {error}")
            
            self.weights = self.weights + self.learning_rate * np.dot(self.X.T,error)
            print(f"Updated Weight: {self.weights}")
                
    def predict(self, X):
        return self.activationFunction(X)
    

## AND Operation

In [3]:
data = {"x1":[0,0,1,1], "x2":[0,1,0,1], "y":[0,0,0,1]}
df = pd.DataFrame(data)
df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [4]:
X = df.iloc[:,:2]
y = df.iloc[:,2]

In [5]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [6]:
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [7]:
model = Perceptron(learning_rate=0.5, bias=0.05, epochs=5)
model.fit(X,y)

Initial Weights : [-0.00015537 -0.00014283]
Epoch 1
Predicted Value [1 1 1 1]
Error 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weight: [-0.50015537 -0.50014283]
Epoch 2
Predicted Value [1 0 0 0]
Error 0   -1
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weight: [-0.00015537 -0.00014283]
Epoch 3
Predicted Value [1 1 1 1]
Error 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weight: [-0.50015537 -0.50014283]
Epoch 4
Predicted Value [1 0 0 0]
Error 0   -1
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weight: [-0.00015537 -0.00014283]
Epoch 5
Predicted Value [1 1 1 1]
Error 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weight: [-0.50015537 -0.50014283]


In [8]:
model.predict(X)

array([1, 0, 0, 0])

In [9]:
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

## **Saving and Loading the Model**

In [11]:
import os
import joblib

dir_ = "Perceptron_model"
os.makedirs(dir_, exist_ok=True)
file_name = os.path.join(dir_, 'AND_model.model')
joblib.dump(model, file_name)

['Perceptron_model/AND_model.model']

In [17]:
loaded_model = joblib.load(file_name)
result = loaded_model.predict(X)
result

array([1, 0, 0, 0])

## **OR Operation**

In [19]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,1]}
df = pd.DataFrame(data)
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [21]:
X = df.iloc[:,:2]
y = df['y']

In [22]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [23]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [25]:
model = Perceptron(learning_rate=0.5, bias=0.01, epochs=5)
model.fit(X,y)

Initial Weights : [ 5.02500267e-05 -1.69858333e-04]
Epoch 1
Predicted Value [1 1 1 1]
Error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight: [ 5.02500267e-05 -1.69858333e-04]
Epoch 2
Predicted Value [1 1 1 1]
Error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight: [ 5.02500267e-05 -1.69858333e-04]
Epoch 3
Predicted Value [1 1 1 1]
Error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight: [ 5.02500267e-05 -1.69858333e-04]
Epoch 4
Predicted Value [1 1 1 1]
Error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight: [ 5.02500267e-05 -1.69858333e-04]
Epoch 5
Predicted Value [1 1 1 1]
Error 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weight: [ 5.02500267e-05 -1.69858333e-04]


In [26]:
model.predict(X)

array([1, 1, 1, 1])

In [27]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

## **XOR Operation**

In [28]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,0]}
df = pd.DataFrame(data)
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [29]:
X = df.iloc[:, :2]
y = df['y']

In [30]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [31]:
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64

In [32]:
model = Perceptron(learning_rate=0.5, bias=0.01, epochs=5)
model.fit(X,y)

Initial Weights : [-7.65758119e-05  6.14153022e-05]
Epoch 1
Predicted Value [1 1 1 1]
Error 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated Weight: [-0.50007658 -0.49993858]
Epoch 2
Predicted Value [1 0 0 0]
Error 0   -1
1    1
2    1
3    0
Name: y, dtype: int64
Updated Weight: [-7.65758119e-05  6.14153022e-05]
Epoch 3
Predicted Value [1 1 1 1]
Error 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated Weight: [-0.50007658 -0.49993858]
Epoch 4
Predicted Value [1 0 0 0]
Error 0   -1
1    1
2    1
3    0
Name: y, dtype: int64
Updated Weight: [-7.65758119e-05  6.14153022e-05]
Epoch 5
Predicted Value [1 1 1 1]
Error 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated Weight: [-0.50007658 -0.49993858]


In [33]:
model.predict(X)

array([1, 0, 0, 0])

In [34]:
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64