## Tensorflow Basic

In [1]:
# Install Tensorflow
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 1.5 MB/s eta 0:00:00m eta 0:00:010:01:01


In [2]:
import tensorflow as tf

2023-08-18 12:06:07.017766: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-18 12:06:07.194728: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-18 12:06:07.195583: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-18 12:06:08.107691: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


### GPU/CPU Check

In [28]:
gpu_list = tf.config.list_physical_devices('GPU')
gpu_list

[]

In [30]:
cpu_list = tf.config.list_physical_devices('CPU')
cpu_list

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

### Check the version

In [2]:
# Check the version
print(f"Tensorlfow Version : {tf.__version__}")
print(f"Keras Version : {tf.keras.__version__}")
print(f"Eager Execution Is : {tf.executing_eagerly()}")

Tensorlfow Version : 2.12.0
Keras Version : 2.12.0
Eager Execution Is : True


### Tensorflow Constant 

In [3]:
# Tensorflow Constant contains three parameters : data, dtype and shape
x = tf.constant(1)
y = tf.constant([1,2,3,4], dtype=tf.float32, shape=[2,2])
x,y

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>)

In [13]:
y.shape

TensorShape([2, 2])

In [14]:
y.dtype

tf.float32

In [15]:
y.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [5]:
type(y.numpy())

numpy.ndarray

### Random Constant

In [45]:
# Normal Distribution
x_rand = tf.random.normal(shape=(10,1), mean=0, stddev=1)
x_rand

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 0.06604511],
       [ 0.4542782 ],
       [-0.14563298],
       [ 1.1440861 ],
       [ 0.29841045],
       [-0.21712814],
       [-0.7914236 ],
       [-0.76791537],
       [-1.8703556 ],
       [-0.47358176]], dtype=float32)>

In [44]:
x_rand.numpy()

array([[-0.5818397 ],
       [-1.7558296 ],
       [ 0.47948423],
       [-0.33096197],
       [-1.4122254 ],
       [-0.34713823],
       [ 0.04052497],
       [ 0.67595303],
       [-0.4493795 ],
       [ 0.05804604]], dtype=float32)

In [10]:
tf.zeros(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [48]:
# Uniform Distribution
x_rand = tf.random.uniform(shape=[10], minval=0, maxval=100)
x_rand

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([46.45287  , 51.489567 , 84.41675  , 52.806377 ,  5.9336066,
       76.44321  , 58.18106  , 90.87975  , 42.225204 , 44.46894  ],
      dtype=float32)>

In [49]:
x_rand.numpy()

array([46.45287  , 51.489567 , 84.41675  , 52.806377 ,  5.9336066,
       76.44321  , 58.18106  , 90.87975  , 42.225204 , 44.46894  ],
      dtype=float32)

### Tensorflow Methods

In [27]:
x = tf.zeros(shape=(2,3), dtype=tf.int32)
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [29]:
x.numpy()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [12]:
x = tf.ones(shape=(2,3), dtype=tf.int32)
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [22]:
x = tf.fill([4,3], 10)
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]], dtype=int32)>

In [33]:
x.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [34]:
y

5

In [36]:
z = tf.add(x,y)
z

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

In [37]:
z.numpy()

array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)