## Tensorflow Basic

In [2]:
import tensorflow as tf

2023-09-10 08:46:18.412666: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-10 08:46:18.571043: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-10 08:46:18.572290: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-10 08:46:19.405466: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


### GPU/CPU Check

In [3]:
gpu_list = tf.config.list_physical_devices('GPU')
gpu_list

[]

In [4]:
cpu_list = tf.config.list_physical_devices('CPU')
cpu_list

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

### Check the version

In [2]:
# Check the version
print(f"Tensorlfow Version : {tf.__version__}")
print(f"Keras Version : {tf.keras.__version__}")
print(f"Eager Execution Is : {tf.executing_eagerly()}")

Tensorlfow Version : 2.12.0
Keras Version : 2.12.0
Eager Execution Is : True


### Tensorflow Constant 

In [5]:
x = tf.constant(42)

In [22]:
x.numpy()

42

In [20]:
x.shape

TensorShape([])

In [21]:
x.dtype

tf.int32

In [6]:
x = tf.constant(42, dtype=tf.float64)
print('Value : ', x.numpy())
print('Shape : ', x.shape)
print('Data Type : ', x.dtype)

Value :  42.0
Shape :  ()
Data Type :  <dtype: 'float64'>


In [3]:
# Tensorflow Constant contains three parameters : data, dtype and shape
x = tf.constant(1)
y = tf.constant([1,2,3,4], dtype=tf.float32, shape=[2,2])
x,y

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>)

In [13]:
y.shape

TensorShape([2, 2])

In [14]:
y.dtype

tf.float32

In [15]:
y.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [5]:
type(y.numpy())

numpy.ndarray

In [11]:
# Add two tensorflow constant
x = tf.constant([[1,2,3,4,5,6]], shape=[2,3])
y = tf.constant([[10,20,30,40,50,50]], shape=[2,3])
z = tf.add(x,y)
print(x.numpy(),'\n')
print(y.numpy(),'\n')
print(z.numpy(),'\n')

[[1 2 3]
 [4 5 6]] 

[[10 20 30]
 [40 50 50]] 

[[11 22 33]
 [44 55 56]] 



In [12]:
x = tf.constant(42)

### Random Constant

In [45]:
# Normal Distribution
x_rand = tf.random.normal(shape=(10,1), mean=0, stddev=1)
x_rand

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 0.06604511],
       [ 0.4542782 ],
       [-0.14563298],
       [ 1.1440861 ],
       [ 0.29841045],
       [-0.21712814],
       [-0.7914236 ],
       [-0.76791537],
       [-1.8703556 ],
       [-0.47358176]], dtype=float32)>

In [44]:
x_rand.numpy()

array([[-0.5818397 ],
       [-1.7558296 ],
       [ 0.47948423],
       [-0.33096197],
       [-1.4122254 ],
       [-0.34713823],
       [ 0.04052497],
       [ 0.67595303],
       [-0.4493795 ],
       [ 0.05804604]], dtype=float32)

In [10]:
tf.zeros(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [48]:
# Uniform Distribution
x_rand = tf.random.uniform(shape=[10], minval=0, maxval=100)
x_rand

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([46.45287  , 51.489567 , 84.41675  , 52.806377 ,  5.9336066,
       76.44321  , 58.18106  , 90.87975  , 42.225204 , 44.46894  ],
      dtype=float32)>

In [49]:
x_rand.numpy()

array([46.45287  , 51.489567 , 84.41675  , 52.806377 ,  5.9336066,
       76.44321  , 58.18106  , 90.87975  , 42.225204 , 44.46894  ],
      dtype=float32)

### Tensorflow Methods

In [27]:
x = tf.zeros(shape=(2,3), dtype=tf.int32)
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [29]:
x.numpy()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [12]:
x = tf.ones(shape=(2,3), dtype=tf.int32)
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [22]:
x = tf.fill([4,3], 10)
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]], dtype=int32)>

In [33]:
x.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [34]:
y

5

In [36]:
z = tf.add(x,y)
z

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

In [37]:
z.numpy()

array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)

In [17]:
named_constant = tf.constant(42.0, name="my_constant")
named_constant

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>


## Tensorflow Variable

In [95]:
a = tf.Variable([1,2,3,4,5,6], dtype=tf.float32, validate_shape=False)
a

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [96]:
a.name

'Variable:0'

In [97]:
a.dtype

tf.float32

In [98]:
a.numpy()

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [94]:
# Create Variable from Constant
a_con = tf.constant([1,2,3,4], shape=(2,2), dtype=tf.float32)
a_var = tf.Variable(a_con)
a_var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [61]:
a_var.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [57]:
# Reshape Variable
tf.reshape(a, (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [113]:
x = tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [114]:
x.numpy()

array([1, 2, 3, 4], dtype=int32)

In [117]:
y = tf.reshape(x, (2,2))

In [118]:
y.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [64]:
# Get Index of highest value
tf.argmax(a_var)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [67]:
# Convert to Tensor
tf.convert_to_tensor(a)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [101]:
# Change Variable Vaues
a.assign([4,5,6,7,8,9])

<tf.Variable 'UnreadVariable' shape=(6,) dtype=float32, numpy=array([4., 5., 6., 7., 8., 9.], dtype=float32)>

In [74]:
a.name

'Variable:0'

In [73]:
a.numpy()

array([4., 5., 6., 7., 8., 9.], dtype=float32)

In [79]:
a_var.assign([[10,20],[30,40]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[10., 20.],
       [30., 40.]], dtype=float32)>

In [77]:
a_var.numpy()

array([[10., 20.],
       [30., 40.]], dtype=float32)

In [90]:
a.numpy()

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [91]:
a.assign_add([6,5,4,3,2,1])

<tf.Variable 'UnreadVariable' shape=(6,) dtype=float32, numpy=array([7., 7., 7., 7., 7., 7.], dtype=float32)>

In [92]:
a

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([7., 7., 7., 7., 7., 7.], dtype=float32)>

## Rank/Dimension of a Tensor

In [155]:
a = tf.Variable([1,2,3,4])
b = tf.Variable([[[1,2,3],[3,4,5],[5,6,7]]])
c = tf.constant([1,2,3,4,5,6])
d = tf.Variable([[[1,2,3],[3,4,5]],[[5,6,7],[10,20,30]]])

In [140]:
tf.rank(a)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [145]:
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [138]:
tf.rank(c)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [153]:
b.shape

TensorShape([1, 3, 3])

In [144]:
b.numpy()

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]]], dtype=int32)

In [150]:
b.numpy()[0][0][1]

2

In [151]:
b[0,0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [156]:
d

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [10, 20, 30]]], dtype=int32)>

In [157]:
tf.rank(d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [164]:
d[1][1][2]

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [165]:
d[1,1,2]

<tf.Tensor: shape=(), dtype=int32, numpy=30>

## Casting Tensor to NumPy/Python Variable

In [171]:
d.numpy()

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [10, 20, 30]]], dtype=int32)

In [169]:
d[1,1,2].numpy()

30

## Tensor Size

In [178]:
tf.size(d)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [179]:
tf.size(d).numpy()

12